package com.example.CenterManagement.dto.training;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Data transfer object representing a domain")
public class DomainDto {

    @Schema(
            description = "Unique identifier of the domain (autogenerated)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY // Indicates this field is read-only and autogenerated
    )
    private Long domainId;

    @NotBlank(message = "Domain name cannot be blank")
    @Size(min = 1, max = 100, message = "Domain name must be between 1 and 100 characters")
    @Schema(
            description = "Name of the domain (must be unique)",
            example = "Strength Training",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String domainName;
}