spring:
  application:
    name: CenterManagement
    offset: 10
    ttl: 120


  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.hnkqawkynropwthullll
    password: despacito123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


  data:
    redis:
      username: default
      port: 15941
      password: 1GcwEcoAa1AGt62hcpzxKmyIj3NNldgR
      host: redis-15941.c250.eu-central-1-1.ec2.redns.redis-cloud.com




  security:
    user:
      name: user
      password: user
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: chihebellefi111@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    password: FZrEvjpXqV4J1th8

server:
  port: 5000
springdoc:
  api-docs:
    enabled: true

