package com.example.CenterManagement.dto.user;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Data transfer object representing an employer")
public class EmployerDto {

    @Schema(
            description = "Unique identifier of the employer (autogenerated)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    private Long id;

    @NotBlank(message = "Employer name cannot be blank")
    @Size(min = 1, max = 255, message = "Employer name must be between 1 and 255 characters")
    @Schema(
            description = "Name of the employer (must be unique)",
            example = "FitLife Gym",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String employerName;
}