package com.example.CenterManagement.dto.user;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Data transfer object for participant")
public class ParticipantDto {

    @Schema(
            description = "Unique identifier of the participant (autogenerated)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY // Indicates this field is read-only and autogenerated
    )
    private Long participantId;

    @Schema(
            description = "Embedded user information",
            implementation = UserDto.class
    )
    private UserDto user;

    @NotBlank(message = "Structure name cannot be blank")
    @Schema(
            description = "Name of the structure associated with the participant",
            example = "FitLife Gym",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private StructureDto structure;

    @NotBlank(message = "Profile cannot be blank")
    @Schema(
            description = "Profile of the participant",
            example = "Fitness Enthusiast",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private ProfileDto profile;
}