package com.example.CenterManagement.dto.user;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Data transfer object representing a profile")
public class ProfileDto {

    @Schema(
            description = "Unique identifier of the profile (autogenerated)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY // Indicates this field is read-only and autogenerated
    )
    private Long profileId;

    @NotBlank(message = "Profile type cannot be blank")
    @Size(min = 1, max = 100, message = "Profile type must be between 1 and 100 characters")
    @Schema(
            description = "Type of the profile (must be unique)",
            example = "Fitness Enthusiast",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String profileType;
}