package com.example.CenterManagement.dto.user;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Data transfer object representing a structure")
public class StructureDto {

    @Schema(
            description = "Unique identifier of the structure (autogenerated)",
            example = "1",
            accessMode = Schema.AccessMode.READ_ONLY // Indicates this field is read-only and autogenerated
    )
    private Long structureId;

    @NotBlank(message = "Structure name cannot be blank")
    @Size(min = 1, max = 100, message = "Structure name must be between 1 and 100 characters")
    @Schema(
            description = "Name of the structure (must be unique)",
            example = "FitLife Gym",
            requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String structureName;
}